Template.chessGame.onRendered(function() {
    var config = {
        position: 'start',
    }

    game = new Chess();

    board = ChessBoard('board', config);

    pgn = this.data.moves;
    currentIndex = 0;

    $(document).on('keypress', function(e) {
        if (e.keyCode == 37) {
            game.undo();

            if (currentIndex != 0) {
                currentIndex--;
            }

            board.position(game.fen());
        }

        if (e.keyCode == 39) {
            var possibleMoves = game.moves();

            if (currentIndex == pgn.length) {
                return false;
            }

            // exit if the game is over
            if (game.game_over() === true ||
                game.in_draw() === true ||
                possibleMoves.length === 0) return;

            game.move(pgn[currentIndex]);
            currentIndex++;
            board.position(game.fen());
        }
    });


});

Template.chessGame.events({
    'click .next': function() {
        var possibleMoves = game.moves();

        if (currentIndex == pgn.length) {
            return false;
        }

        // exit if the game is over
        if (game.game_over() === true ||
            game.in_draw() === true ||
            possibleMoves.length === 0) return;

        game.move(pgn[currentIndex]);
        currentIndex++;
        board.position(game.fen());
    },

    'click .prev': function() {
        game.undo();

        if (currentIndex != 0) {
            currentIndex--;
        }

        board.position(game.fen());
    },

    'click .flip': function() {
        board.flip();
    },

    'click .end': function() {
        while (currentIndex < pgn.length) {
            game.move(pgn[currentIndex]);
            currentIndex++;
        }

        board.position(game.fen());
    },

    'click .start': function() {
        while (currentIndex > -1) {
            game.undo();
            currentIndex--;
        }

        board.position(game.fen());
    },

    'keypress input': function(event) {
        if (event.keyCode == 13) {
            alert('you hit enter');
            event.stopPropagation();
            return false;
        }
    }

});

Template.chessGame.helpers({

    eco_mapping: function(eco_code) {
        eco_dict = {
            "A00": "Uncommon Opening", 
            "A01": "Nimzovich-Larsen Attack", 
            "A02": "Bird's Opening", 
            "A03": "Bird's Opening", 
            "A04": "Reti Opening", 
            "A05": "Reti Opening", 
            "A06": "Reti Opening", 
            "A07": "King's Indian Attack", 
            "A08": "King's Indian Attack", 
            "A09": "Reti Opening", 
            "A10": "English", 
            "A11": "English, Caro-Kann Defensive System", 
            "A12": "English with b3", 
            "A13": "English", 
            "A14": "English", 
            "A15": "English", 
            "A16": "English", 
            "A17": "English", 
            "A18": "English, Mikenas-Carls", 
            "A19": "English, Mikenas-Carls, Sicilian Variation", 
            "A20": "English", 
            "A21": "English", 
            "A22": "English", 
            "A23": "English, Bremen System, Keres Variation", 
            "A24": "English, Bremen System with ...g6", 
            "A25": "English", 
            "A26": "English", 
            "A27": "English, Three Knights System", 
            "A28": "English", 
            "A29": "English, Four Knights, Kingside Fianchetto", 
            "A30": "English, Symmetrical", 
            "A31": "English, Symmetrical, Benoni Formation", 
            "A32": "English, Symmetrical Variation", 
            "A33": "English, Symmetrical", 
            "A34": "English, Symmetrical", 
            "A35": "English, Symmetrical", 
            "A36": "English", 
            "A37": "English, Symmetrical", 
            "A38": "English, Symmetrical", 
            "A39": "English, Symmetrical, Main line with d4", 
            "A40": "Queen's Pawn Game", 
            "A41": "Queen's Pawn Game (with ...d6)", 
            "A42": "Modern Defense, Averbakh System", 
            "A43": "Old Benoni", 
            "A44": "Old Benoni Defense", 
            "A45": "Queen's Pawn Game", 
            "A46": "Queen's Pawn Game", 
            "A47": "Queen's Indian", 
            "A48": "King's Indian", 
            "A49": "King's Indian, Fianchetto without c4", 
            "A50": "Queen's Pawn Game", 
            "A51": "Budapest Gambit", 
            "A52": "Budapest Gambit", 
            "A53": "Old Indian", 
            "A54": "Old Indian, Ukrainian Variation, 4.Nf3", 
            "A55": "Old Indian, Main line", 
            "A56": "Benoni Defense", 
            "A57": "Benko Gambit", 
            "A58": "Benko Gambit", 
            "A59": "Benko Gambit", 
            "A60": "Benoni Defense", 
            "A61": "Benoni", 
            "A62": "Benoni, Fianchetto Variation", 
            "A63": "Benoni, Fianchetto, 9...Nbd7", 
            "A64": "Benoni, Fianchetto, 11...Re8", 
            "A65": "Benoni, 6.e4", 
            "A66": "Benoni", 
            "A67": "Benoni, Taimanov Variation", 
            "A68": "Benoni, Four Pawns Attack", 
            "A69": "Benoni, Four Pawns Attack, Main line", 
            "A70": "Benoni, Classical with 7.Nf3", 
            "A71": "Benoni, Classical, 8.Bg5", 
            "A72": "Benoni, Classical without 9.O-O", 
            "A73": "Benoni, Classical, 9.O-O", 
            "A74": "Benoni, Classical, 9...a6, 10.a4", 
            "A75": "Benoni, Classical with ...a6 and 10...Bg4", 
            "A76": "Benoni, Classical, 9...Re8", 
            "A77": "Benoni, Classical, 9...Re8, 10.Nd2", 
            "A78": "Benoni, Classical with ...Re8 and ...Na6", 
            "A79": "Benoni, Classical, 11.f3", 
            "A80": "Dutch", 
            "A81": "Dutch", 
            "A82": "Dutch, Staunton Gambit", 
            "A83": "Dutch, Staunton Gambit", 
            "A84": "Dutch", 
            "A85": "Dutch, with c4 & Nc3", 
            "A86": "Dutch", 
            "A87": "Dutch, Leningrad, Main Variation", 
            "A88": "Dutch, Leningrad, Main Variation with c6", 
            "A89": "Dutch, Leningrad, Main Variation with Nc6", 
            "A90": "Dutch", 
            "A91": "Dutch Defense", 
            "A92": "Dutch", 
            "A93": "Dutch, Stonewall, Botvinnik Variation", 
            "A94": "Dutch, Stonewall with Ba3", 
            "A95": "Dutch, Stonewall", 
            "A96": "Dutch, Classical Variation", 
            "A97": "Dutch, Ilyin-Genevsky", 
            "A98": "Dutch, Ilyin-Genevsky Variation with Qc2", 
            "A99": "Dutch, Ilyin-Genevsky Variation with b3", 
            "B00": "Uncommon King's Pawn Opening", 
            "B01": "Scandinavian", 
            "B02": "Alekhine's Defense", 
            "B03": "Alekhine's Defense", 
            "B04": "Alekhine's Defense, Modern", 
            "B05": "Alekhine's Defense, Modern", 
            "B06": "Robatsch", 
            "B07": "Pirc", 
            "B08": "Pirc, Classical", 
            "B09": "Pirc, Austrian Attack", 
            "B10": "Caro-Kann", 
            "B11": "Caro-Kann, Two Knights, 3...Bg4", 
            "B12": "Caro-Kann Defense", 
            "B13": "Caro-Kann, Exchange", 
            "B14": "Caro-Kann, Panov-Botvinnik Attack", 
            "B15": "Caro-Kann", 
            "B16": "Caro-Kann, Bronstein-Larsen Variation", 
            "B17": "Caro-Kann, Steinitz Variation", 
            "B18": "Caro-Kann, Classical", 
            "B19": "Caro-Kann, Classical", 
            "B20": "Sicilian", 
            "B21": "Sicilian, 2.f4 and 2.d4", 
            "B22": "Sicilian, Alapin", 
            "B23": "Sicilian, Closed", 
            "B24": "Sicilian, Closed", 
            "B25": "Sicilian, Closed", 
            "B26": "Sicilian, Closed, 6.Be3", 
            "B27": "Sicilian", 
            "B28": "Sicilian, O'Kelly Variation", 
            "B29": "Sicilian, Nimzovich-Rubinstein", 
            "B30": "Sicilian", 
            "B31": "Sicilian, Rossolimo Variation", 
            "B32": "Sicilian", 
            "B33": "Sicilian", 
            "B34": "Sicilian, Accelerated Fianchetto", 
            "B35": "Sicilian, Accelerated Fianchetto, Modern Variation with Bc4", 
            "B36": "Sicilian, Accelerated Fianchetto", 
            "B37": "Sicilian, Accelerated Fianchetto", 
            "B38": "Sicilian, Accelerated Fianchetto, Maroczy Bind, 6.Be3", 
            "B39": "Sicilian, Accelerated Fianchetto, Breyer Variation", 
            "B40": "Sicilian", 
            "B41": "Sicilian, Kan", 
            "B42": "Sicilian, Kan", 
            "B43": "Sicilian, Kan, 5.Nc3", 
            "B44": "Sicilian", 
            "B45": "Sicilian, Taimanov", 
            "B46": "Sicilian, Taimanov Variation", 
            "B47": "Sicilian, Taimanov (Bastrikov) Variation", 
            "B48": "Sicilian, Taimanov Variation", 
            "B49": "Sicilian, Taimanov Variation", 
            "B50": "Sicilian", 
            "B51": "Sicilian, Canal-Sokolsky (Rossolimo) Attack", 
            "B52": "Sicilian, Canal-Sokolsky (Rossolimo) Attack", 
            "B53": "Sicilian", 
            "B54": "Sicilian", 
            "B55": "Sicilian, Prins Variation, Venice Attack", 
            "B56": "Sicilian", 
            "B57": "Sicilian", 
            "B58": "Sicilian", 
            "B59": "Sicilian, Boleslavsky Variation, 7.Nb3", 
            "B60": "Sicilian, Richter-Rauzer", 
            "B61": "Sicilian, Richter-Rauzer, Larsen Variation, 7.Qd2", 
            "B62": "Sicilian, Richter-Rauzer", 
            "B63": "Sicilian, Richter-Rauzer Attack", 
            "B64": "Sicilian, Richter-Rauzer Attack", 
            "B65": "Sicilian, Richter-Rauzer Attack, 7...Be7 Defense, 9...Nxd4", 
            "B66": "Sicilian, Richter-Rauzer Attack, 7...a6", 
            "B67": "Sicilian, Richter-Rauzer Attack, 7...a6 Defense, 8...Bd7", 
            "B68": "Sicilian, Richter-Rauzer Attack, 7...a6 Defense, 9...Be7", 
            "B69": "Sicilian, Richter-Rauzer Attack, 7...a6 Defense, 11.Bxf6", 
            "B70": "Sicilian, Dragon Variation", 
            "B71": "Sicilian, Dragon, Levenfish Variation", 
            "B72": "Sicilian, Dragon", 
            "B73": "Sicilian, Dragon, Classical", 
            "B74": "Sicilian, Dragon, Classical", 
            "B75": "Sicilian, Dragon, Yugoslav Attack", 
            "B76": "Sicilian, Dragon, Yugoslav Attack", 
            "B77": "Sicilian, Dragon, Yugoslav Attack", 
            "B78": "Sicilian, Dragon, Yugoslav Attack, 10.castle long", 
            "B79": "Sicilian, Dragon, Yugoslav Attack, 12.h4", 
            "B80": "Sicilian, Scheveningen", 
            "B81": "Sicilian, Scheveningen, Keres Attack", 
            "B82": "Sicilian, Scheveningen", 
            "B83": "Sicilian", 
            "B84": "Sicilian, Scheveningen", 
            "B85": "Sicilian, Scheveningen, Classical", 
            "B86": "Sicilian, Fischer-Sozin Attack", 
            "B87": "Sicilian, Fischer-Sozin with ...a6 and ...b5", 
            "B88": "Sicilian, Fischer-Sozin Attack", 
            "B89": "Sicilian", 
            "B90": "Sicilian, Najdorf", 
            "B91": "Sicilian, Najdorf, Zagreb (Fianchetto) Variation", 
            "B92": "Sicilian, Najdorf, Opocensky Variation", 
            "B93": "Sicilian, Najdorf, 6.f4", 
            "B94": "Sicilian, Najdorf", 
            "B95": "Sicilian, Najdorf, 6...e6", 
            "B96": "Sicilian, Najdorf", 
            "B97": "Sicilian, Najdorf", 
            "B98": "Sicilian, Najdorf", 
            "B99": "Sicilian, Najdorf, 7...Be7 Main line", 
            "C00": "French Defense", 
            "C01": "French, Exchange", 
            "C02": "French, Advance", 
            "C03": "French, Tarrasch", 
            "C04": "French, Tarrasch, Guimard Main line", 
            "C05": "French, Tarrasch", 
            "C06": "French, Tarrasch", 
            "C07": "French, Tarrasch", 
            "C08": "French, Tarrasch, Open, 4.ed ed", 
            "C09": "French, Tarrasch, Open Variation, Main line", 
            "C10": "French", 
            "C11": "French", 
            "C12": "French, McCutcheon", 
            "C13": "French", 
            "C14": "French, Classical", 
            "C15": "French, Winawer", 
            "C16": "French, Winawer", 
            "C17": "French, Winawer, Advance", 
            "C18": "French, Winawer", 
            "C19": "French, Winawer, Advance", 
            "C20": "King's Pawn Game", 
            "C21": "Center Game", 
            "C22": "Center Game", 
            "C23": "Bishop's Opening", 
            "C24": "Bishop's Opening", 
            "C25": "Vienna", 
            "C26": "Vienna", 
            "C27": "Vienna Game", 
            "C28": "Vienna Game", 
            "C29": "Vienna Gambit", 
            "C30": "King's Gambit Declined", 
            "C31": "King's Gambit Declined, Falkbeer Counter Gambit", 
            "C32": "King's Gambit Declined, Falkbeer Counter Gambit", 
            "C33": "King's Gambit Accepted", 
            "C34": "King's Gambit Accepted", 
            "C35": "King's Gambit Accepted, Cunningham", 
            "C36": "King's Gambit Accepted, Abbazia Defense", 
            "C37": "King's Gambit Accepted", 
            "C38": "King's Gambit Accepted", 
            "C39": "King's Gambit Accepted", 
            "C40": "King's Knight Opening", 
            "C41": "Philidor Defense", 
            "C42": "Petrov Defense", 
            "C43": "Petrov, Modern Attack", 
            "C44": "King's Pawn Game", 
            "C45": "Scotch Game", 
            "C46": "Three Knights", 
            "C47": "Four Knights", 
            "C48": "Four Knights", 
            "C49": "Four Knights", 
            "C50": "Giuoco Piano", 
            "C51": "Evans Gambit", 
            "C52": "Evans Gambit", 
            "C53": "Giuoco Piano", 
            "C54": "Giuoco Piano", 
            "C55": "Two Knights Defense", 
            "C56": "Two Knights", 
            "C57": "Two Knights", 
            "C58": "Two Knights", 
            "C59": "Two Knights", 
            "C60": "Ruy Lopez", 
            "C61": "Ruy Lopez, Bird's Defense", 
            "C62": "Ruy Lopez, Old Steinitz Defense", 
            "C63": "Ruy Lopez, Schliemann Defense", 
            "C64": "Ruy Lopez, Classical", 
            "C65": "Ruy Lopez, Berlin Defense", 
            "C66": "Ruy Lopez", 
            "C67": "Ruy Lopez", 
            "C68": "Ruy Lopez, Exchange", 
            "C69": "Ruy Lopez, Exchange, Gligoric Variation, 6.d4", 
            "C70": "Ruy Lopez", 
            "C71": "Ruy Lopez", 
            "C72": "Ruy Lopez, Modern Steinitz Defense, 5.O-O", 
            "C73": "Ruy Lopez, Modern Steinitz Defense", 
            "C74": "Ruy Lopez, Modern Steinitz Defense", 
            "C75": "Ruy Lopez, Modern Steinitz Defense", 
            "C76": "Ruy Lopez, Modern Steinitz Defense, Fianchetto Variation", 
            "C77": "Ruy Lopez", 
            "C78": "Ruy Lopez", 
            "C79": "Ruy Lopez, Steinitz Defense Deferred", 
            "C80": "Ruy Lopez, Open", 
            "C81": "Ruy Lopez, Open, Howell Attack", 
            "C82": "Ruy Lopez, Open", 
            "C83": "Ruy Lopez, Open", 
            "C84": "Ruy Lopez, Closed", 
            "C85": "Ruy Lopez, Exchange Variation Doubly Deferred (DERLD)", 
            "C86": "Ruy Lopez, Worrall Attack", 
            "C87": "Ruy Lopez", 
            "C88": "Ruy Lopez", 
            "C89": "Ruy Lopez, Marshall", 
            "C90": "Ruy Lopez, Closed", 
            "C91": "Ruy Lopez, Closed", 
            "C92": "Ruy Lopez, Closed", 
            "C93": "Ruy Lopez, Closed, Smyslov Defense", 
            "C94": "Ruy Lopez, Closed, Breyer Defense", 
            "C95": "Ruy Lopez, Closed, Breyer", 
            "C96": "Ruy Lopez, Closed", 
            "C97": "Ruy Lopez, Closed, Chigorin", 
            "C98": "Ruy Lopez, Closed, Chigorin", 
            "C99": "Ruy Lopez, Closed, Chigorin, 12...cd", 
            "D00": "Queen's Pawn Game", 
            "D01": "Richter-Veresov Attack", 
            "D02": "Queen's Pawn Game", 
            "D03": "Torre Attack (Tartakower Variation)", 
            "D04": "Queen's Pawn Game", 
            "D05": "Queen's Pawn Game", 
            "D06": "Queen's Gambit Declined", 
            "D07": "Queen's Gambit Declined, Chigorin Defense", 
            "D08": "Queen's Gambit Declined, Albin Counter Gambit", 
            "D09": "Queen's Gambit Declined, Albin Counter Gambit, 5.g3", 
            "D10": "Queen's Gambit Declined Slav", 
            "D11": "Queen's Gambit Declined Slav", 
            "D12": "Queen's Gambit Declined Slav", 
            "D13": "Queen's Gambit Declined Slav, Exchange Variation", 
            "D14": "Queen's Gambit Declined Slav, Exchange Variation", 
            "D15": "Queen's Gambit Declined Slav", 
            "D16": "Queen's Gambit Declined Slav", 
            "D17": "Queen's Gambit Declined Slav", 
            "D18": "Queen's Gambit Declined Slav, Dutch", 
            "D19": "Queen's Gambit Declined Slav, Dutch", 
            "D20": "Queen's Gambit Accepted", 
            "D21": "Queen's Gambit Accepted", 
            "D22": "Queen's Gambit Accepted", 
            "D23": "Queen's Gambit Accepted", 
            "D24": "Queen's Gambit Accepted", 
            "D25": "Queen's Gambit Accepted", 
            "D26": "Queen's Gambit Accepted", 
            "D27": "Queen's Gambit Accepted, Classical", 
            "D28": "Queen's Gambit Accepted, Classical", 
            "D29": "Queen's Gambit Accepted, Classical", 
            "D30": "Queen's Gambit Declined", 
            "D31": "Queen's Gambit Declined", 
            "D32": "Queen's Gambit Declined, Tarrasch", 
            "D33": "Queen's Gambit Declined, Tarrasch", 
            "D34": "Queen's Gambit Declined, Tarrasch", 
            "D35": "Queen's Gambit Declined", 
            "D36": "Queen's Gambit Declined, Exchange, Positional line, 6.Qc2", 
            "D37": "Queen's Gambit Declined", 
            "D38": "Queen's Gambit Declined, Ragozin Variation", 
            "D39": "Queen's Gambit Declined, Ragozin, Vienna Variation", 
            "D40": "Queen's Gambit Declined, Semi-Tarrasch", 
            "D41": "Queen's Gambit Declined, Semi-Tarrasch", 
            "D42": "Queen's Gambit Declined, Semi-Tarrasch, 7.Bd3", 
            "D43": "Queen's Gambit Declined Semi-Slav", 
            "D44": "Queen's Gambit Declined Semi-Slav", 
            "D45": "Queen's Gambit Declined Semi-Slav", 
            "D46": "Queen's Gambit Declined Semi-Slav", 
            "D47": "Queen's Gambit Declined Semi-Slav", 
            "D48": "Queen's Gambit Declined Semi-Slav, Meran", 
            "D49": "Queen's Gambit Declined Semi-Slav, Meran", 
            "D50": "Queen's Gambit Declined", 
            "D51": "Queen's Gambit Declined", 
            "D52": "Queen's Gambit Declined", 
            "D53": "Queen's Gambit Declined", 
            "D54": "Queen's Gambit Declined, Anti-Neo-Orthodox Variation", 
            "D55": "Queen's Gambit Declined", 
            "D56": "Queen's Gambit Declined", 
            "D57": "Queen's Gambit Declined, Lasker Defense", 
            "D58": "Queen's Gambit Declined, Tartakower (Makagonov-Bondarevsky) System", 
            "D59": "Queen's Gambit Declined, Tartakower", 
            "D60": "Queen's Gambit Declined, Orthodox Defense", 
            "D61": "Queen's Gambit Declined, Orthodox, Rubinstein Attack", 
            "D62": "Queen's Gambit Declined, Orthodox, Rubinstein Attack", 
            "D63": "Queen's Gambit Declined, Orthodox Defense", 
            "D64": "Queen's Gambit Declined, Orthodox, Rubinstein Attack", 
            "D65": "Queen's Gambit Declined, Orthodox, Rubinstein Attack, Main line", 
            "D66": "Queen's Gambit Declined, Orthodox Defense, Bd3 line", 
            "D67": "Queen's Gambit Declined, Orthodox Defense, Bd3 line", 
            "D68": "Queen's Gambit Declined, Orthodox Defense, Classical", 
            "D69": "Queen's Gambit Declined, Orthodox Defense, Classical, 13.de", 
            "D70": "Neo-Grunfeld Defense", 
            "D71": "Neo-Grunfeld", 
            "D72": "Neo-Grunfeld, 5.cd, Main line", 
            "D73": "Neo-Grunfeld, 5.Nf3", 
            "D74": "Neo-Grunfeld, 6.cd Nxd5, 7.O-O", 
            "D75": "Neo-Grunfeld, 6.cd Nxd5, 7.O-O c5, 8.dxc5", 
            "D76": "Neo-Grunfeld, 6.cd Nxd5, 7.O-O Nb6", 
            "D77": "Neo-Grunfeld, 6.O-O", 
            "D78": "Neo-Grunfeld, 6.O-O c6", 
            "D79": "Neo-Grunfeld, 6.O-O, Main line", 
            "D80": "Grunfeld", 
            "D81": "Grunfeld, Russian Variation", 
            "D82": "Grunfeld, 4.Bf4", 
            "D83": "Grunfeld, Grunfeld Gambit", 
            "D84": "Grunfeld, Grunfeld Gambit Accepted", 
            "D85": "Grunfeld", 
            "D86": "Grunfeld, Exchange", 
            "D87": "Grunfeld, Exchange", 
            "D88": "Grunfeld, Spassky Variation, Main line, 10...cd, 11.cd", 
            "D89": "Grunfeld", 
            "D90": "Grunfeld", 
            "D91": "Grunfeld, 5.Bg5", 
            "D92": "Grunfeld, 5.Bf4", 
            "D93": "Grunfeld, with Bf4 & e3", 
            "D94": "Grunfeld", 
            "D95": "Grunfeld", 
            "D96": "Grunfeld, Russian Variation", 
            "D97": "Grunfeld, Russian", 
            "D98": "Grunfeld, Russian", 
            "D99": "Grunfeld Defense, Smyslov", 
            "E00": "Queen's Pawn Game", 
            "E01": "Catalan, Closed", 
            "E02": "Catalan, Open, 5.Qa4", 
            "E03": "Catalan, Open", 
            "E04": "Catalan, Open, 5.Nf3", 
            "E05": "Catalan, Open, Classical line", 
            "E06": "Catalan, Closed, 5.Nf3", 
            "E07": "Catalan, Closed", 
            "E08": "Catalan, Closed", 
            "E09": "Catalan, Closed", 
            "E10": "Queen's Pawn Game", 
            "E11": "Bogo-Indian Defense", 
            "E12": "Queen's Indian", 
            "E13": "Queen's Indian, 4.Nc3, Main line", 
            "E14": "Queen's Indian", 
            "E15": "Queen's Indian", 
            "E16": "Queen's Indian", 
            "E17": "Queen's Indian", 
            "E18": "Queen's Indian, Old Main line, 7.Nc3", 
            "E19": "Queen's Indian, Old Main line, 9.Qxc3", 
            "E20": "Nimzo-Indian", 
            "E21": "Nimzo-Indian, Three Knights", 
            "E22": "Nimzo-Indian, Spielmann Variation", 
            "E23": "Nimzo-Indian, Spielmann", 
            "E24": "Nimzo-Indian, Samisch", 
            "E25": "Nimzo-Indian, Samisch", 
            "E26": "Nimzo-Indian, Samisch", 
            "E27": "Nimzo-Indian, Samisch Variation", 
            "E28": "Nimzo-Indian, Samisch Variation", 
            "E29": "Nimzo-Indian, Samisch", 
            "E30": "Nimzo-Indian, Leningrad", 
            "E31": "Nimzo-Indian, Leningrad, Main line", 
            "E32": "Nimzo-Indian, Classical", 
            "E33": "Nimzo-Indian, Classical", 
            "E34": "Nimzo-Indian, Classical, Noa Variation", 
            "E35": "Nimzo-Indian, Classical, Noa Variation, 5.cd ed", 
            "E36": "Nimzo-Indian, Classical", 
            "E37": "Nimzo-Indian, Classical", 
            "E38": "Nimzo-Indian, Classical, 4...c5", 
            "E39": "Nimzo-Indian, Classical, Pirc Variation", 
            "E40": "Nimzo-Indian, 4.e3", 
            "E41": "Nimzo-Indian", 
            "E42": "Nimzo-Indian, 4.e3 c5, 5.Ne2 (Rubinstein)", 
            "E43": "Nimzo-Indian, Fischer Variation", 
            "E44": "Nimzo-Indian, Fischer Variation, 5.Ne2", 
            "E45": "Nimzo-Indian, 4.e3, Bronstein (Byrne) Variation", 
            "E46": "Nimzo-Indian", 
            "E47": "Nimzo-Indian, 4.e3 O-O 5.Bd3", 
            "E48": "Nimzo-Indian, 4.e3 O-O 5.Bd3 d5", 
            "E49": "Nimzo-Indian, 4.e3, Botvinnik System", 
            "E50": "Nimzo-Indian, 4.e3 O-O 5.Nf3, without ...d5", 
            "E51": "Nimzo-Indian, 4.e3", 
            "E52": "Nimzo-Indian, 4.e3, Main line with ...b6", 
            "E53": "Nimzo-Indian, 4.e3", 
            "E54": "Nimzo-Indian, 4.e3, Gligoric System", 
            "E55": "Nimzo-Indian, 4.e3, Gligoric System, Bronstein Variation", 
            "E56": "Nimzo-Indian, 4.e3, Main line with 7...Nc6", 
            "E57": "Nimzo-Indian, 4.e3, Main line with 8...dc and 9...cd", 
            "E58": "Nimzo-Indian, 4.e3, Main line with 8...Bxc3", 
            "E59": "Nimzo-Indian, 4.e3, Main line", 
            "E60": "King's Indian Defense", 
            "E61": "King's Indian", 
            "E62": "King's Indian, Fianchetto", 
            "E63": "King's Indian, Fianchetto, Panno Variation", 
            "E64": "King's Indian, Fianchetto, Yugoslav System", 
            "E65": "King's Indian, Fianchetto, Yugoslav, 7.O-O", 
            "E66": "King's Indian, Fianchetto, Yugoslav Panno", 
            "E67": "King's Indian, Fianchetto", 
            "E68": "King's Indian, Fianchetto, Classical Variation, 8.e4", 
            "E69": "King's Indian, Fianchetto, Classical Main line", 
            "E70": "King's Indian", 
            "E71": "King's Indian, Makagonov System (5.h3)", 
            "E72": "King's Indian", 
            "E73": "King's Indian", 
            "E74": "King's Indian, Averbakh, 6...c5", 
            "E75": "King's Indian, Averbakh, Main line", 
            "E76": "King's Indian, Four Pawns Attack", 
            "E77": "King's Indian", 
            "E78": "King's Indian, Four Pawns Attack, with Be2 and Nf3", 
            "E79": "King's Indian, Four Pawns Attack, Main line", 
            "E80": "King's Indian, Samisch Variation", 
            "E81": "King's Indian, Samisch", 
            "E82": "King's Indian, Samisch, double Fianchetto Variation", 
            "E83": "King's Indian, Samisch", 
            "E84": "King's Indian, Samisch, Panno Main line", 
            "E85": "King's Indian, Samisch, Orthodox Variation", 
            "E86": "King's Indian, Samisch, Orthodox, 7.Nge2 c6", 
            "E87": "King's Indian, Samisch, Orthodox", 
            "E88": "King's Indian, Samisch, Orthodox, 7.d5 c6", 
            "E89": "King's Indian, Samisch, Orthodox Main line", 
            "E90": "King's Indian", 
            "E91": "King's Indian", 
            "E92": "King's Indian", 
            "E93": "King's Indian, Petrosian System", 
            "E94": "King's Indian, Orthodox", 
            "E95": "King's Indian, Orthodox, 7...Nbd7, 8.Re1", 
            "E96": "King's Indian, Orthodox, 7...Nbd7, Main line", 
            "E97": "King's Indian", 
            "E98": "King's Indian, Orthodox, Taimanov, 9.Ne1", 
            "E99": "King's Indian, Orthodox, Taimanov"
        }

        return eco_dict[eco_code];
    }

});